server:
  port: 8082

spring:
  application:
    name: schedule-service
  data:
    mongodb:
      username: admin
      database: fuel_db
      port: 27017
      host: localhost
  kafka:
    consumer:
      group-id: group-Id
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

order:
  topic:
    name: orders-topic

auto:
  create:
    topics:
      enable: true