server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Praveen-Fernando/spring-cloud-config-storerepo.git
          search-paths:
            - 'primary-config-store/*service'