management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdb2?createDatabaseIfNotExsist
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      naming:
#        physical-strategy:
#      ddl-auto: create


